apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-app
  labels:
    app: restaurante-app
spec:
  template:
    metadata:
      name: restaurante-app
      labels:
        app: restaurante-app
    spec:
      containers:
        - name: restaurante-app-container
          image: marcelobenjamim/restaurante-app:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: restaurante-config
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: restaurante-secret
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: restaurante-secret
                key: DB_USER      
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 1000
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-app