apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurante-config
data:
  DB_HOST: "postgres-restaurante.cfkdflarlyzz.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres_restaurante"
