apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init-restaurante-schema.sql: |
    -- conteúdo do init-restaurante-schema.sql
    DO $$
    BEGIN
      IF NOT EXISTS(
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name = 'restaurante_schema'
      ) THEN
          EXECUTE 'CREATE SCHEMA restaurante_schema';
      END IF;
    END 
    $$;

  02-db_schema.sql: |
    -- conteúdo do db_schema.sql
    CREATE TABLE restaurante_schema.Clientes (
      id SERIAL,
      nome VARCHAR(255),
      email VARCHAR(255),
      telefone VARCHAR(20),
      cpf VARCHAR(14),
      endereco TEXT,
      data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id)
    );

    CREATE TABLE restaurante_schema.Produtos (
        id SERIAL,
        nome VARCHAR(255) NOT NULL,
        categoria VARCHAR(255),
        preco DECIMAL(10, 2) NOT NULL,
        descricao TEXT,
        imagem TEXT,
        data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    );

    CREATE TABLE restaurante_schema.Pedidos (
        id SERIAL,
        cliente_id INT,
        status VARCHAR(50),
        data_hora_inclusao_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        FOREIGN KEY (cliente_id) REFERENCES restaurante_schema.Clientes(id)
    );

    CREATE TABLE restaurante_schema.Pagamentos (
        id SERIAL,
        pedido_id INT NOT NULL,
        valor DECIMAL(10, 2) NOT NULL,
        id_mercado_pago VARCHAR(255),
        status VARCHAR(50),
        data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        FOREIGN KEY (pedido_id) REFERENCES restaurante_schema.Pedidos(id)
    );

    CREATE TABLE restaurante_schema.Associacao_Pedido_Produto (
        pedido_id INT NOT NULL,
        produtos_id INT NOT NULL,
        quantidade INT NOT NULL,
        preco DECIMAL(10, 2) NOT NULL,
        PRIMARY KEY (pedido_id, produtos_id),
        FOREIGN KEY (pedido_id) REFERENCES restaurante_schema.Pedidos(id),
        FOREIGN KEY (produtos_id) REFERENCES restaurante_schema.Produtos(id)
    );
