apiVersion: v1
kind: Pod
metadata:
  name: test-client
spec:
  dnsPolicy: ClusterFirst
  containers:
    - name: busybox
      image: busybox:1.35
      command:
        - sh
        - -c
        - "sleep 3600"  # Mantém o pod vivo por 1 hora
  restartPolicy: Never