apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-app
  labels:
    app: restaurante-app
spec:
  template:
    metadata:
      name: restaurante-app
      labels:
        app: restaurante-app
    spec:
      containers:
        - name: restaurante-app-container
          image: marcelobenjamim/restaurante-app:v1
          ports:
            - containerPort: 8080         
          
          resources:
            requests:
              cpu: 1m
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-app