name: CI/CD Pipeline

on:
  push:
    branches: ["main"] # roda só quando fizer push na main
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar JDK (se for Java, ajuste conforme sua stack)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Rodar build e testes (Maven como exemplo)
      - name: Build with Maven
        run: mvn -B clean verify

      # 4. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build da imagem
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/restaurante-app
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # 6. Push da imagem
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/restaurante-app
          IMAGE_TAG=${{ github.sha }}
          docker push $IMAGE_NAME:$IMAGE_TAG

      # 7. (Opcional) também marcar como "latest"
      - name: Tag as latest
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/restaurante-app
          IMAGE_TAG=${{ github.sha }}
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest